# Runs the specified categories for the given device.

name: Category Base

on:
  workflow_call:
    inputs:
      connection:
        description: 'Run the Connection test category'
        default: false
        required: false
        type: boolean
      wall-configuration:
        description: 'Run the Wall Configuration test category'
        default: false
        required: false
        type: boolean
      source-configuration:
        description: 'Run the Source Configuration test category'
        default: false
        required: false
        type: boolean
      preset-configuration:
        description: 'Run the Preset Configuration test category'
        default: false
        required: false
        type: boolean
      edid-minder:
        description: 'Run the EDID Minder test category'
        default: false
        required: false
        type: boolean
      device-settings:
        description: 'Run the Device Settings test category'
        default: false
        required: false
        type: boolean
      app-menu:
        description: 'Run the Application Menu test category'
        default: false
        required: false
        type: boolean


jobs:
    connection:
      name: Connection
      if: ${{ inputs.connection == true }} 
      uses: ./.github/workflows/base.yml
      with:
        build-name: ${{ github.job.name }}
        test-filter: TestCategory=Connection
        
    wall-configuration:
      name: Wall Configuration
      if: ${{ inputs.wall-configuration == true }} 
      uses: ./.github/workflows/base.yml
      with:
        build-name: ${{ github.job.name }}
        test-filter: TestCategory=WallConfiguration
        
        
#  category_matrix:
#    strategy:
#      fail-fast: false
#      matrix:
#        category: [ 'Connection', 'WallConfiguration', 'SourceConfiguration', 'PresetConfiguration', 'EDIDMinder', 'DeviceSettings', 'ApplicationMenu' ]
#    name: ${{ matrix.category }}
#    uses: ./.github/workflows/base.yml
#    with:
#      build-name: ${{ matrix.category }}
#      test-filter: TestCategory=${{ matrix.category }}