name: Nightly (Windows 11)

on:
  schedule:
    - cron:  '30 21 * * *'

jobs:
  build:

    runs-on: [self-hosted, win11]

    steps:
      - uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
