name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  quantum-build:
    uses: ./.github/workflows/base.yml
    name: Quantum Tests
    with:
      test-filter: TestCategory=Quantum

  mgp-build:
    uses: ./.github/workflows/base.yml
    name: MGP Tests
    with:
      test-filter: TestCategory=MGP
