name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  quantum-build:
    runs-on: [ self-hosted, win10 ]
    uses: ./.github/workflows/base.yml
    with:
      config-path: TestCategory=Quantum

  mgp-build:
    runs-on: [ self-hosted, win10 ]
    uses: ./.github/workflows/base.yml
    with:
      config-path: TestCategory=MGP
