name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  category_matrix:
    strategy:
      fail-fast: false
      matrix:
        category: [ 'MGP', 'Quantum' ]
    name: ${{ matrix.category }} Tests
    uses: ./.github/workflows/categorybase.yml
    with:
      connection: true