name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  category_matrix:
    strategy:
      matrix:
        category: [ 'MGP', 'Quantum' ]
    uses: ./.github/workflows/base.yml
    with:
      build-name: ${{ matrix.version }}
      test-filter: TestCategory=${{ matrix.version }}

#  quantum-build:
#    name: Quantum Tests
    

#  mgp-build:
#    uses: ./.github/workflows/base.yml
#    name: MGP Tests
#    with:
#      build-name: 
#      test-filter: TestCategory=MGP
