name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, win10]

    steps:
    - uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Screenshots
        path: Images
