name: OnChange

on:
  push:
    branches: [ "master" ] # Temp - remove this
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, win10]

    steps:
    - uses: actions/checkout@v3

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: Images

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults
      if: ${{ always() }} # Always run this step to publish test results even when there are test failures
